### ISSUE TITLE
The coordinates are wrong but the angle of the source is right

### ISSUE THREAD

**Issue by zhaoforever** [introlab/manyears#3]
Hi, I'm trying to use my 6 circular microphone array for voice location tracking. The coordinates(X,Y,Z) of manyears provided are wrong,for example, I stand 3m from the microphones but the results are 0.5m. However, the angle of the voice source is correct. So have you ever met this problem?
Thanks.

**Comment by FrancoisGrondin** [comment]
Hi,

If I understand your statement, the direction is correct but the distance isn't? If that is the case, this is normal: ManyEars provide the direction only, and not the distance. This is due to the far field effect: since your microphones are close to each other (compared to the distance between the array and the sound source), the phase difference provides us with the direction only. ManyEars always returns a direction in terms of a normalized vector (which magnitude is 1.0). If you calculate X^2 + Y^2 + Z^2 from the coordinates obtained, this should sum to 1.

Let me know if this answers your question,

**Comment by zhaoforever** [comment]
@FrancoisGrondin Thanks for your answers.
